on: [push, tag]

name: Continuous integration

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_sha: true
          add_git_labels: true
          tags: latest

      - name: Smoke Test
        run:
          - docker run ${{ github.repository}}:latest mdbook --version
          - docker run ${{ github.repository}}:latest mdbook-linkcheck --version
